const inputArray = [
    [{
        "url": "https://arb1.arbitrum.io/rpc",
        "method": "eth_gasPrice",
        "status": 200
    }, {
        "url": "https://rpc.ankr.com/arbitrum",
        "method": "eth_gasPrice",
        "status": 200
    }, {
        "url": "https://1rpc.io/arb",
        "method": "eth_gasPrice",
        "status": 200
    }, {
        "url": "https://arb-mainnet.g.alchemy.com/v2/demo",
        "method": "eth_gasPrice",
        "status": 200
    }, {
        "url": "https://arbitrum.blockpi.network/v1/rpc/public",
        "method": "eth_gasPrice",
        "status": 200
    }, {
        "url": "https://arbitrum-one.public.blastapi.io",
        "method": "eth_gasPrice",
        "status": 200
    }, {
        "url": "https://endpoints.omniatech.io/v1/arbitrum/one/public",
        "method": "eth_gasPrice",
        "status": 200
    }, {
        "url": "https://arb-mainnet-public.unifra.io",
        "method": "eth_gasPrice",
        "status": 200
    }, {
        "url": "https://arbitrum.api.onfinality.io/public",
        "method": "eth_gasPrice",
        "status": 200
    }, {
        "url": "https://rpc.arb1.arbitrum.gateway.fm",
        "method": "eth_gasPrice",
        "status": 200
    }, {
        "url": "https://arbitrum-one.publicnode.com",
        "method": "eth_gasPrice",
        "status": 200
    }, {
        "url": "https://arbitrum.meowrpc.com",
        "method": "eth_gasPrice",
        "status": 200
    }, {
        "url": "https://api.zan.top/node/v1/arb/one/public",
        "method": "eth_gasPrice",
        "status": 200
    }, {
        "url": "https://arbitrum.drpc.org",
        "method": "eth_gasPrice",
        "status": 200
    }],
    [{
        "url": "https://arb1.arbitrum.io/rpc",
        "method": "eth_blockNumber",
        "status": 200
    }, {
        "url": "https://rpc.ankr.com/arbitrum",
        "method": "eth_blockNumber",
        "status": 200
    }, {
        "url": "https://1rpc.io/arb",
        "method": "eth_blockNumber",
        "status": 200
    }, {
        "url": "https://arb-mainnet.g.alchemy.com/v2/demo",
        "method": "eth_blockNumber",
        "status": 200
    }, {
        "url": "https://arbitrum.blockpi.network/v1/rpc/public",
        "method": "eth_blockNumber",
        "status": 200
    }, {
        "url": "https://arbitrum-one.public.blastapi.io",
        "method": "eth_blockNumber",
        "status": 200
    }, {
        "url": "https://endpoints.omniatech.io/v1/arbitrum/one/public",
        "method": "eth_blockNumber",
        "status": 200
    }, {
        "url": "https://arb-mainnet-public.unifra.io",
        "method": "eth_blockNumber",
        "status": 200
    }, {
        "url": "https://arbitrum.api.onfinality.io/public",
        "method": "eth_blockNumber",
        "status": 200
    }, {
        "url": "https://rpc.arb1.arbitrum.gateway.fm",
        "method": "eth_blockNumber",
        "status": 200
    }, {
        "url": "https://arbitrum-one.publicnode.com",
        "method": "eth_blockNumber",
        "status": 200
    }, {
        "url": "https://arbitrum.meowrpc.com",
        "method": "eth_blockNumber",
        "status": 200
    }, {
        "url": "https://api.zan.top/node/v1/arb/one/public",
        "method": "eth_blockNumber",
        "status": 200
    }, {
        "url": "https://arbitrum.drpc.org",
        "method": "eth_blockNumber",
        "status": 200
    }],
    [{
        "url": "https://arb1.arbitrum.io/rpc",
        "method": "eth_getBlockByHash",
        "status": 200
    }, {
        "url": "https://rpc.ankr.com/arbitrum",
        "method": "eth_getBlockByHash",
        "status": 200
    }, {
        "url": "https://1rpc.io/arb",
        "method": "eth_getBlockByHash",
        "status": 200
    }, {
        "url": "https://arbitrum.blockpi.network/v1/rpc/public",
        "method": "eth_getBlockByHash",
        "status": 200
    }, {
        "url": "https://arbitrum-one.public.blastapi.io",
        "method": "eth_getBlockByHash",
        "status": 200
    }, {
        "url": "https://endpoints.omniatech.io/v1/arbitrum/one/public",
        "method": "eth_getBlockByHash",
        "status": 200
    }, {
        "url": "https://arb-mainnet-public.unifra.io",
        "method": "eth_getBlockByHash",
        "status": 200
    }, {
        "url": "https://arbitrum.api.onfinality.io/public",
        "method": "eth_getBlockByHash",
        "status": 200
    }, {
        "url": "https://rpc.arb1.arbitrum.gateway.fm",
        "method": "eth_getBlockByHash",
        "status": 200
    }, {
        "url": "https://arbitrum-one.publicnode.com",
        "method": "eth_getBlockByHash",
        "status": 200
    }, {
        "url": "https://arbitrum.meowrpc.com",
        "method": "eth_getBlockByHash",
        "status": 200
    }, {
        "url": "https://api.zan.top/node/v1/arb/one/public",
        "method": "eth_getBlockByHash",
        "status": 200
    }, {
        "url": "https://arbitrum.drpc.org",
        "method": "eth_getBlockByHash",
        "status": 200
    }],
    [{
        "url": "https://arb1.arbitrum.io/rpc",
        "method": "eth_getBlockByNumber",
        "status": 200
    }, {
        "url": "https://rpc.ankr.com/arbitrum",
        "method": "eth_getBlockByNumber",
        "status": 200
    }, {
        "url": "https://1rpc.io/arb",
        "method": "eth_getBlockByNumber",
        "status": 200
    }, {
        "url": "https://arbitrum.blockpi.network/v1/rpc/public",
        "method": "eth_getBlockByNumber",
        "status": 200
    }, {
        "url": "https://arbitrum-one.public.blastapi.io",
        "method": "eth_getBlockByNumber",
        "status": 200
    }, {
        "url": "https://endpoints.omniatech.io/v1/arbitrum/one/public",
        "method": "eth_getBlockByNumber",
        "status": 200
    }, {
        "url": "https://arb-mainnet-public.unifra.io",
        "method": "eth_getBlockByNumber",
        "status": 200
    }, {
        "url": "https://arbitrum.api.onfinality.io/public",
        "method": "eth_getBlockByNumber",
        "status": 200
    }, {
        "url": "https://rpc.arb1.arbitrum.gateway.fm",
        "method": "eth_getBlockByNumber",
        "status": 200
    }, {
        "url": "https://arbitrum-one.publicnode.com",
        "method": "eth_getBlockByNumber",
        "status": 200
    }, {
        "url": "https://arbitrum.meowrpc.com",
        "method": "eth_getBlockByNumber",
        "status": 200
    }, {
        "url": "https://api.zan.top/node/v1/arb/one/public",
        "method": "eth_getBlockByNumber",
        "status": 200
    }, {
        "url": "https://arbitrum.drpc.org",
        "method": "eth_getBlockByNumber",
        "status": 200
    }],
    [{
        "url": "https://arb1.arbitrum.io/rpc",
        "method": "eth_chainId",
        "status": 200
    }, {
        "url": "https://rpc.ankr.com/arbitrum",
        "method": "eth_chainId",
        "status": 200
    }, {
        "url": "https://1rpc.io/arb",
        "method": "eth_chainId",
        "status": 200
    }, {
        "url": "https://arb-mainnet.g.alchemy.com/v2/demo",
        "method": "eth_chainId",
        "status": 200
    }, {
        "url": "https://arbitrum.blockpi.network/v1/rpc/public",
        "method": "eth_chainId",
        "status": 200
    }, {
        "url": "https://arbitrum-one.public.blastapi.io",
        "method": "eth_chainId",
        "status": 200
    }, {
        "url": "https://endpoints.omniatech.io/v1/arbitrum/one/public",
        "method": "eth_chainId",
        "status": 200
    }, {
        "url": "https://arb-mainnet-public.unifra.io",
        "method": "eth_chainId",
        "status": 200
    }, {
        "url": "https://arbitrum.api.onfinality.io/public",
        "method": "eth_chainId",
        "status": 200
    }, {
        "url": "https://rpc.arb1.arbitrum.gateway.fm",
        "method": "eth_chainId",
        "status": 200
    }, {
        "url": "https://arbitrum-one.publicnode.com",
        "method": "eth_chainId",
        "status": 200
    }, {
        "url": "https://arbitrum.meowrpc.com",
        "method": "eth_chainId",
        "status": 200
    }, {
        "url": "https://api.zan.top/node/v1/arb/one/public",
        "method": "eth_chainId",
        "status": 200
    }, {
        "url": "https://arbitrum.drpc.org",
        "method": "eth_chainId",
        "status": 200
    }],
    [{
        "url": "https://arb1.arbitrum.io/rpc",
        "method": "eth_feeHistory",
        "status": 200
    }, {
        "url": "https://rpc.ankr.com/arbitrum",
        "method": "eth_feeHistory",
        "status": 200
    }, {
        "url": "https://1rpc.io/arb",
        "method": "eth_feeHistory",
        "status": 200
    }, {
        "url": "https://arb-mainnet.g.alchemy.com/v2/demo",
        "method": "eth_feeHistory",
        "status": 200
    }, {
        "url": "https://arbitrum.blockpi.network/v1/rpc/public",
        "method": "eth_feeHistory",
        "status": 200
    }, {
        "url": "https://arbitrum-one.public.blastapi.io",
        "method": "eth_feeHistory",
        "status": 200
    }, {
        "url": "https://endpoints.omniatech.io/v1/arbitrum/one/public",
        "method": "eth_feeHistory",
        "status": 200
    }, {
        "url": "https://arb-mainnet-public.unifra.io",
        "method": "eth_feeHistory",
        "status": 200
    }, {
        "url": "https://arbitrum.api.onfinality.io/public",
        "method": "eth_feeHistory",
        "status": 200
    }, {
        "url": "https://rpc.arb1.arbitrum.gateway.fm",
        "method": "eth_feeHistory",
        "status": 200
    }, {
        "url": "https://arbitrum-one.publicnode.com",
        "method": "eth_feeHistory",
        "status": 200
    }, {
        "url": "https://arbitrum.meowrpc.com",
        "method": "eth_feeHistory",
        "status": 200
    }, {
        "url": "https://arbitrum.drpc.org",
        "method": "eth_feeHistory",
        "status": 200
    }],
    [{
        "url": "https://arb1.arbitrum.io/rpc",
        "method": "eth_getBalance",
        "status": 200
    }, {
        "url": "https://rpc.ankr.com/arbitrum",
        "method": "eth_getBalance",
        "status": 200
    }, {
        "url": "https://1rpc.io/arb",
        "method": "eth_getBalance",
        "status": 200
    }, {
        "url": "https://arb-mainnet.g.alchemy.com/v2/demo",
        "method": "eth_getBalance",
        "status": 200
    }, {
        "url": "https://arbitrum.blockpi.network/v1/rpc/public",
        "method": "eth_getBalance",
        "status": 200
    }, {
        "url": "https://arbitrum-one.public.blastapi.io",
        "method": "eth_getBalance",
        "status": 200
    }, {
        "url": "https://endpoints.omniatech.io/v1/arbitrum/one/public",
        "method": "eth_getBalance",
        "status": 200
    }, {
        "url": "https://arb-mainnet-public.unifra.io",
        "method": "eth_getBalance",
        "status": 200
    }, {
        "url": "https://arbitrum.api.onfinality.io/public",
        "method": "eth_getBalance",
        "status": 200
    }, {
        "url": "https://rpc.arb1.arbitrum.gateway.fm",
        "method": "eth_getBalance",
        "status": 200
    }, {
        "url": "https://arbitrum-one.publicnode.com",
        "method": "eth_getBalance",
        "status": 200
    }, {
        "url": "https://arbitrum.meowrpc.com",
        "method": "eth_getBalance",
        "status": 200
    }, {
        "url": "https://api.zan.top/node/v1/arb/one/public",
        "method": "eth_getBalance",
        "status": 200
    }, {
        "url": "https://arbitrum.drpc.org",
        "method": "eth_getBalance",
        "status": 200
    }],
    [{
        "url": "https://arb1.arbitrum.io/rpc",
        "method": "eth_getBlockTransactionCountByHash",
        "status": 200
    }, {
        "url": "https://rpc.ankr.com/arbitrum",
        "method": "eth_getBlockTransactionCountByHash",
        "status": 200
    }, {
        "url": "https://1rpc.io/arb",
        "method": "eth_getBlockTransactionCountByHash",
        "status": 200
    }, {
        "url": "https://arb-mainnet.g.alchemy.com/v2/demo",
        "method": "eth_getBlockTransactionCountByHash",
        "status": 200
    }, {
        "url": "https://arbitrum.blockpi.network/v1/rpc/public",
        "method": "eth_getBlockTransactionCountByHash",
        "status": 200
    }, {
        "url": "https://arbitrum-one.public.blastapi.io",
        "method": "eth_getBlockTransactionCountByHash",
        "status": 200
    }, {
        "url": "https://endpoints.omniatech.io/v1/arbitrum/one/public",
        "method": "eth_getBlockTransactionCountByHash",
        "status": 200
    }, {
        "url": "https://arb-mainnet-public.unifra.io",
        "method": "eth_getBlockTransactionCountByHash",
        "status": 200
    }, {
        "url": "https://arbitrum.api.onfinality.io/public",
        "method": "eth_getBlockTransactionCountByHash",
        "status": 200
    }, {
        "url": "https://rpc.arb1.arbitrum.gateway.fm",
        "method": "eth_getBlockTransactionCountByHash",
        "status": 200
    }, {
        "url": "https://arbitrum-one.publicnode.com",
        "method": "eth_getBlockTransactionCountByHash",
        "status": 200
    }, {
        "url": "https://arbitrum.meowrpc.com",
        "method": "eth_getBlockTransactionCountByHash",
        "status": 200
    }, {
        "url": "https://api.zan.top/node/v1/arb/one/public",
        "method": "eth_getBlockTransactionCountByHash",
        "status": 200
    }, {
        "url": "https://arbitrum.drpc.org",
        "method": "eth_getBlockTransactionCountByHash",
        "status": 200
    }],
    [{
        "url": "https://arb1.arbitrum.io/rpc",
        "method": "eth_getBlockTransactionCountByNumber",
        "status": 200
    }, {
        "url": "https://rpc.ankr.com/arbitrum",
        "method": "eth_getBlockTransactionCountByNumber",
        "status": 200
    }, {
        "url": "https://1rpc.io/arb",
        "method": "eth_getBlockTransactionCountByNumber",
        "status": 200
    }, {
        "url": "https://arb-mainnet.g.alchemy.com/v2/demo",
        "method": "eth_getBlockTransactionCountByNumber",
        "status": 200
    }, {
        "url": "https://arbitrum.blockpi.network/v1/rpc/public",
        "method": "eth_getBlockTransactionCountByNumber",
        "status": 200
    }, {
        "url": "https://arbitrum-one.public.blastapi.io",
        "method": "eth_getBlockTransactionCountByNumber",
        "status": 200
    }, {
        "url": "https://endpoints.omniatech.io/v1/arbitrum/one/public",
        "method": "eth_getBlockTransactionCountByNumber",
        "status": 200
    }, {
        "url": "https://arb-mainnet-public.unifra.io",
        "method": "eth_getBlockTransactionCountByNumber",
        "status": 200
    }, {
        "url": "https://arbitrum.api.onfinality.io/public",
        "method": "eth_getBlockTransactionCountByNumber",
        "status": 200
    }, {
        "url": "https://rpc.arb1.arbitrum.gateway.fm",
        "method": "eth_getBlockTransactionCountByNumber",
        "status": 200
    }, {
        "url": "https://arbitrum-one.publicnode.com",
        "method": "eth_getBlockTransactionCountByNumber",
        "status": 200
    }, {
        "url": "https://arbitrum.meowrpc.com",
        "method": "eth_getBlockTransactionCountByNumber",
        "status": 200
    }, {
        "url": "https://api.zan.top/node/v1/arb/one/public",
        "method": "eth_getBlockTransactionCountByNumber",
        "status": 200
    }, {
        "url": "https://arbitrum.drpc.org",
        "method": "eth_getBlockTransactionCountByNumber",
        "status": 200
    }],
    [{
        "url": "https://arb1.arbitrum.io/rpc",
        "method": "eth_getCode",
        "status": 200
    }, {
        "url": "https://rpc.ankr.com/arbitrum",
        "method": "eth_getCode",
        "status": 200
    }, {
        "url": "https://1rpc.io/arb",
        "method": "eth_getCode",
        "status": 200
    }, {
        "url": "https://arb-mainnet.g.alchemy.com/v2/demo",
        "method": "eth_getCode",
        "status": 200
    }, {
        "url": "https://arbitrum.blockpi.network/v1/rpc/public",
        "method": "eth_getCode",
        "status": 200
    }, {
        "url": "https://arbitrum-one.public.blastapi.io",
        "method": "eth_getCode",
        "status": 200
    }, {
        "url": "https://endpoints.omniatech.io/v1/arbitrum/one/public",
        "method": "eth_getCode",
        "status": 200
    }, {
        "url": "https://arb-mainnet-public.unifra.io",
        "method": "eth_getCode",
        "status": 200
    }, {
        "url": "https://arbitrum.api.onfinality.io/public",
        "method": "eth_getCode",
        "status": 200
    }, {
        "url": "https://rpc.arb1.arbitrum.gateway.fm",
        "method": "eth_getCode",
        "status": 200
    }, {
        "url": "https://arbitrum-one.publicnode.com",
        "method": "eth_getCode",
        "status": 200
    }, {
        "url": "https://arbitrum.meowrpc.com",
        "method": "eth_getCode",
        "status": 200
    }, {
        "url": "https://api.zan.top/node/v1/arb/one/public",
        "method": "eth_getCode",
        "status": 200
    }, {
        "url": "https://arbitrum.drpc.org",
        "method": "eth_getCode",
        "status": 200
    }],
    [{
        "url": "https://arb1.arbitrum.io/rpc",
        "method": "eth_getLogs",
        "status": 200
    }, {
        "url": "https://rpc.ankr.com/arbitrum",
        "method": "eth_getLogs",
        "status": 200
    }, {
        "url": "https://1rpc.io/arb",
        "method": "eth_getLogs",
        "status": 200
    }, {
        "url": "https://arb-mainnet.g.alchemy.com/v2/demo",
        "method": "eth_getLogs",
        "status": 200
    }, {
        "url": "https://arbitrum.blockpi.network/v1/rpc/public",
        "method": "eth_getLogs",
        "status": 200
    }, {
        "url": "https://endpoints.omniatech.io/v1/arbitrum/one/public",
        "method": "eth_getLogs",
        "status": 200
    }, {
        "url": "https://arb-mainnet-public.unifra.io",
        "method": "eth_getLogs",
        "status": 200
    }, {
        "url": "https://arbitrum.api.onfinality.io/public",
        "method": "eth_getLogs",
        "status": 200
    }, {
        "url": "https://rpc.arb1.arbitrum.gateway.fm",
        "method": "eth_getLogs",
        "status": 200
    }, {
        "url": "https://arbitrum-one.publicnode.com",
        "method": "eth_getLogs",
        "status": 200
    }, {
        "url": "https://arbitrum.meowrpc.com",
        "method": "eth_getLogs",
        "status": 200
    }, {
        "url": "https://arbitrum.drpc.org",
        "method": "eth_getLogs",
        "status": 200
    }],
    [{
        "url": "https://arb1.arbitrum.io/rpc",
        "method": "eth_getProof",
        "status": 200
    }, {
        "url": "https://rpc.ankr.com/arbitrum",
        "method": "eth_getProof",
        "status": 200
    }, {
        "url": "https://1rpc.io/arb",
        "method": "eth_getProof",
        "status": 200
    }, {
        "url": "https://arbitrum.blockpi.network/v1/rpc/public",
        "method": "eth_getProof",
        "status": 200
    }, {
        "url": "https://arbitrum-one.public.blastapi.io",
        "method": "eth_getProof",
        "status": 200
    }, {
        "url": "https://endpoints.omniatech.io/v1/arbitrum/one/public",
        "method": "eth_getProof",
        "status": 200
    }, {
        "url": "https://arb-mainnet-public.unifra.io",
        "method": "eth_getProof",
        "status": 200
    }, {
        "url": "https://arbitrum.api.onfinality.io/public",
        "method": "eth_getProof",
        "status": 200
    }, {
        "url": "https://arbitrum-one.publicnode.com",
        "method": "eth_getProof",
        "status": 200
    }, {
        "url": "https://arbitrum.meowrpc.com",
        "method": "eth_getProof",
        "status": 200
    }, {
        "url": "https://arbitrum.drpc.org",
        "method": "eth_getProof",
        "status": 200
    }],
    [{
        "url": "https://arb1.arbitrum.io/rpc",
        "method": "eth_getStorageAt",
        "status": 200
    }, {
        "url": "https://rpc.ankr.com/arbitrum",
        "method": "eth_getStorageAt",
        "status": 200
    }, {
        "url": "https://1rpc.io/arb",
        "method": "eth_getStorageAt",
        "status": 200
    }, {
        "url": "https://arb-mainnet.g.alchemy.com/v2/demo",
        "method": "eth_getStorageAt",
        "status": 200
    }, {
        "url": "https://arbitrum.blockpi.network/v1/rpc/public",
        "method": "eth_getStorageAt",
        "status": 200
    }, {
        "url": "https://arbitrum-one.public.blastapi.io",
        "method": "eth_getStorageAt",
        "status": 200
    }, {
        "url": "https://endpoints.omniatech.io/v1/arbitrum/one/public",
        "method": "eth_getStorageAt",
        "status": 200
    }, {
        "url": "https://arb-mainnet-public.unifra.io",
        "method": "eth_getStorageAt",
        "status": 200
    }, {
        "url": "https://arbitrum.api.onfinality.io/public",
        "method": "eth_getStorageAt",
        "status": 200
    }, {
        "url": "https://rpc.arb1.arbitrum.gateway.fm",
        "method": "eth_getStorageAt",
        "status": 200
    }, {
        "url": "https://arbitrum-one.publicnode.com",
        "method": "eth_getStorageAt",
        "status": 200
    }, {
        "url": "https://arbitrum.meowrpc.com",
        "method": "eth_getStorageAt",
        "status": 200
    }],
    [{
        "url": "https://arb1.arbitrum.io/rpc",
        "method": "eth_getTransactionByBlockHashAndIndex",
        "status": 200
    }, {
        "url": "https://rpc.ankr.com/arbitrum",
        "method": "eth_getTransactionByBlockHashAndIndex",
        "status": 200
    }, {
        "url": "https://1rpc.io/arb",
        "method": "eth_getTransactionByBlockHashAndIndex",
        "status": 200
    }, {
        "url": "https://arbitrum.blockpi.network/v1/rpc/public",
        "method": "eth_getTransactionByBlockHashAndIndex",
        "status": 200
    }, {
        "url": "https://arbitrum-one.public.blastapi.io",
        "method": "eth_getTransactionByBlockHashAndIndex",
        "status": 200
    }, {
        "url": "https://endpoints.omniatech.io/v1/arbitrum/one/public",
        "method": "eth_getTransactionByBlockHashAndIndex",
        "status": 200
    }, {
        "url": "https://arb-mainnet-public.unifra.io",
        "method": "eth_getTransactionByBlockHashAndIndex",
        "status": 200
    }, {
        "url": "https://arbitrum.api.onfinality.io/public",
        "method": "eth_getTransactionByBlockHashAndIndex",
        "status": 200
    }, {
        "url": "https://rpc.arb1.arbitrum.gateway.fm",
        "method": "eth_getTransactionByBlockHashAndIndex",
        "status": 200
    }, {
        "url": "https://arbitrum-one.publicnode.com",
        "method": "eth_getTransactionByBlockHashAndIndex",
        "status": 200
    }, {
        "url": "https://arbitrum.meowrpc.com",
        "method": "eth_getTransactionByBlockHashAndIndex",
        "status": 200
    }, {
        "url": "https://api.zan.top/node/v1/arb/one/public",
        "method": "eth_getTransactionByBlockHashAndIndex",
        "status": 200
    }, {
        "url": "https://arbitrum.drpc.org",
        "method": "eth_getTransactionByBlockHashAndIndex",
        "status": 200
    }],
    [{
        "url": "https://arb1.arbitrum.io/rpc",
        "method": "eth_getTransactionByBlockNumberAndIndex",
        "status": 200
    }, {
        "url": "https://rpc.ankr.com/arbitrum",
        "method": "eth_getTransactionByBlockNumberAndIndex",
        "status": 200
    }, {
        "url": "https://1rpc.io/arb",
        "method": "eth_getTransactionByBlockNumberAndIndex",
        "status": 200
    }, {
        "url": "https://arbitrum.blockpi.network/v1/rpc/public",
        "method": "eth_getTransactionByBlockNumberAndIndex",
        "status": 200
    }, {
        "url": "https://arbitrum-one.public.blastapi.io",
        "method": "eth_getTransactionByBlockNumberAndIndex",
        "status": 200
    }, {
        "url": "https://endpoints.omniatech.io/v1/arbitrum/one/public",
        "method": "eth_getTransactionByBlockNumberAndIndex",
        "status": 200
    }, {
        "url": "https://arb-mainnet-public.unifra.io",
        "method": "eth_getTransactionByBlockNumberAndIndex",
        "status": 200
    }, {
        "url": "https://arbitrum.api.onfinality.io/public",
        "method": "eth_getTransactionByBlockNumberAndIndex",
        "status": 200
    }, {
        "url": "https://rpc.arb1.arbitrum.gateway.fm",
        "method": "eth_getTransactionByBlockNumberAndIndex",
        "status": 200
    }, {
        "url": "https://arbitrum-one.publicnode.com",
        "method": "eth_getTransactionByBlockNumberAndIndex",
        "status": 200
    }, {
        "url": "https://arbitrum.meowrpc.com",
        "method": "eth_getTransactionByBlockNumberAndIndex",
        "status": 200
    }, {
        "url": "https://api.zan.top/node/v1/arb/one/public",
        "method": "eth_getTransactionByBlockNumberAndIndex",
        "status": 200
    }, {
        "url": "https://arbitrum.drpc.org",
        "method": "eth_getTransactionByBlockNumberAndIndex",
        "status": 200
    }],
    [{
        "url": "https://arb1.arbitrum.io/rpc",
        "method": "eth_getTransactionByHash",
        "status": 200
    }, {
        "url": "https://rpc.ankr.com/arbitrum",
        "method": "eth_getTransactionByHash",
        "status": 200
    }, {
        "url": "https://1rpc.io/arb",
        "method": "eth_getTransactionByHash",
        "status": 200
    }, {
        "url": "https://arb-mainnet.g.alchemy.com/v2/demo",
        "method": "eth_getTransactionByHash",
        "status": 200
    }, {
        "url": "https://arbitrum.blockpi.network/v1/rpc/public",
        "method": "eth_getTransactionByHash",
        "status": 200
    }, {
        "url": "https://arbitrum-one.public.blastapi.io",
        "method": "eth_getTransactionByHash",
        "status": 200
    }, {
        "url": "https://endpoints.omniatech.io/v1/arbitrum/one/public",
        "method": "eth_getTransactionByHash",
        "status": 200
    }, {
        "url": "https://arb-mainnet-public.unifra.io",
        "method": "eth_getTransactionByHash",
        "status": 200
    }, {
        "url": "https://arbitrum.api.onfinality.io/public",
        "method": "eth_getTransactionByHash",
        "status": 200
    }, {
        "url": "https://rpc.arb1.arbitrum.gateway.fm",
        "method": "eth_getTransactionByHash",
        "status": 200
    }, {
        "url": "https://arbitrum-one.publicnode.com",
        "method": "eth_getTransactionByHash",
        "status": 200
    }, {
        "url": "https://arbitrum.meowrpc.com",
        "method": "eth_getTransactionByHash",
        "status": 200
    }, {
        "url": "https://api.zan.top/node/v1/arb/one/public",
        "method": "eth_getTransactionByHash",
        "status": 200
    }, {
        "url": "https://arbitrum.drpc.org",
        "method": "eth_getTransactionByHash",
        "status": 200
    }],
    [{
        "url": "https://arb1.arbitrum.io/rpc",
        "method": "eth_getTransactionCount",
        "status": 200
    }, {
        "url": "https://rpc.ankr.com/arbitrum",
        "method": "eth_getTransactionCount",
        "status": 200
    }, {
        "url": "https://1rpc.io/arb",
        "method": "eth_getTransactionCount",
        "status": 200
    }, {
        "url": "https://arb-mainnet.g.alchemy.com/v2/demo",
        "method": "eth_getTransactionCount",
        "status": 200
    }, {
        "url": "https://arbitrum.blockpi.network/v1/rpc/public",
        "method": "eth_getTransactionCount",
        "status": 200
    }, {
        "url": "https://arbitrum-one.public.blastapi.io",
        "method": "eth_getTransactionCount",
        "status": 200
    }, {
        "url": "https://endpoints.omniatech.io/v1/arbitrum/one/public",
        "method": "eth_getTransactionCount",
        "status": 200
    }, {
        "url": "https://arb-mainnet-public.unifra.io",
        "method": "eth_getTransactionCount",
        "status": 200
    }, {
        "url": "https://arbitrum.api.onfinality.io/public",
        "method": "eth_getTransactionCount",
        "status": 200
    }, {
        "url": "https://rpc.arb1.arbitrum.gateway.fm",
        "method": "eth_getTransactionCount",
        "status": 200
    }, {
        "url": "https://arbitrum-one.publicnode.com",
        "method": "eth_getTransactionCount",
        "status": 200
    }, {
        "url": "https://arbitrum.meowrpc.com",
        "method": "eth_getTransactionCount",
        "status": 200
    }, {
        "url": "https://arbitrum.drpc.org",
        "method": "eth_getTransactionCount",
        "status": 200
    }],
    [{
        "url": "https://arb1.arbitrum.io/rpc",
        "method": "eth_getTransactionReceipt",
        "status": 200
    }, {
        "url": "https://rpc.ankr.com/arbitrum",
        "method": "eth_getTransactionReceipt",
        "status": 200
    }, {
        "url": "https://1rpc.io/arb",
        "method": "eth_getTransactionReceipt",
        "status": 200
    }, {
        "url": "https://arbitrum.blockpi.network/v1/rpc/public",
        "method": "eth_getTransactionReceipt",
        "status": 200
    }, {
        "url": "https://arbitrum-one.public.blastapi.io",
        "method": "eth_getTransactionReceipt",
        "status": 200
    }, {
        "url": "https://endpoints.omniatech.io/v1/arbitrum/one/public",
        "method": "eth_getTransactionReceipt",
        "status": 200
    }, {
        "url": "https://arb-mainnet-public.unifra.io",
        "method": "eth_getTransactionReceipt",
        "status": 200
    }, {
        "url": "https://arbitrum.api.onfinality.io/public",
        "method": "eth_getTransactionReceipt",
        "status": 200
    }, {
        "url": "https://rpc.arb1.arbitrum.gateway.fm",
        "method": "eth_getTransactionReceipt",
        "status": 200
    }, {
        "url": "https://arbitrum-one.publicnode.com",
        "method": "eth_getTransactionReceipt",
        "status": 200
    }, {
        "url": "https://arbitrum.meowrpc.com",
        "method": "eth_getTransactionReceipt",
        "status": 200
    }, {
        "url": "https://api.zan.top/node/v1/arb/one/public",
        "method": "eth_getTransactionReceipt",
        "status": 200
    }, {
        "url": "https://arbitrum.drpc.org",
        "method": "eth_getTransactionReceipt",
        "status": 200
    }],
    [{
        "url": "https://rpc.ankr.com/arbitrum",
        "method": "eth_getUncleCountByBlockHash",
        "status": 200
    }, {
        "url": "https://1rpc.io/arb",
        "method": "eth_getUncleCountByBlockHash",
        "status": 200
    }, {
        "url": "https://arbitrum.blockpi.network/v1/rpc/public",
        "method": "eth_getUncleCountByBlockHash",
        "status": 200
    }, {
        "url": "https://arbitrum-one.public.blastapi.io",
        "method": "eth_getUncleCountByBlockHash",
        "status": 200
    }, {
        "url": "https://endpoints.omniatech.io/v1/arbitrum/one/public",
        "method": "eth_getUncleCountByBlockHash",
        "status": 200
    }, {
        "url": "https://arb-mainnet-public.unifra.io",
        "method": "eth_getUncleCountByBlockHash",
        "status": 200
    }, {
        "url": "https://arbitrum.api.onfinality.io/public",
        "method": "eth_getUncleCountByBlockHash",
        "status": 200
    }, {
        "url": "https://rpc.arb1.arbitrum.gateway.fm",
        "method": "eth_getUncleCountByBlockHash",
        "status": 200
    }, {
        "url": "https://arbitrum-one.publicnode.com",
        "method": "eth_getUncleCountByBlockHash",
        "status": 200
    }, {
        "url": "https://arbitrum.meowrpc.com",
        "method": "eth_getUncleCountByBlockHash",
        "status": 200
    }, {
        "url": "https://api.zan.top/node/v1/arb/one/public",
        "method": "eth_getUncleCountByBlockHash",
        "status": 200
    }, {
        "url": "https://arbitrum.drpc.org",
        "method": "eth_getUncleCountByBlockHash",
        "status": 200
    }],
    [{
        "url": "https://rpc.ankr.com/arbitrum",
        "method": "eth_getUncleCountByBlockNumber",
        "status": 200
    }, {
        "url": "https://1rpc.io/arb",
        "method": "eth_getUncleCountByBlockNumber",
        "status": 200
    }, {
        "url": "https://arb-mainnet.g.alchemy.com/v2/demo",
        "method": "eth_getUncleCountByBlockNumber",
        "status": 200
    }, {
        "url": "https://arbitrum.blockpi.network/v1/rpc/public",
        "method": "eth_getUncleCountByBlockNumber",
        "status": 200
    }, {
        "url": "https://arbitrum-one.public.blastapi.io",
        "method": "eth_getUncleCountByBlockNumber",
        "status": 200
    }, {
        "url": "https://endpoints.omniatech.io/v1/arbitrum/one/public",
        "method": "eth_getUncleCountByBlockNumber",
        "status": 200
    }, {
        "url": "https://arb-mainnet-public.unifra.io",
        "method": "eth_getUncleCountByBlockNumber",
        "status": 200
    }, {
        "url": "https://arbitrum.api.onfinality.io/public",
        "method": "eth_getUncleCountByBlockNumber",
        "status": 200
    }, {
        "url": "https://rpc.arb1.arbitrum.gateway.fm",
        "method": "eth_getUncleCountByBlockNumber",
        "status": 200
    }, {
        "url": "https://arbitrum-one.publicnode.com",
        "method": "eth_getUncleCountByBlockNumber",
        "status": 200
    }, {
        "url": "https://arbitrum.meowrpc.com",
        "method": "eth_getUncleCountByBlockNumber",
        "status": 200
    }, {
        "url": "https://api.zan.top/node/v1/arb/one/public",
        "method": "eth_getUncleCountByBlockNumber",
        "status": 200
    }, {
        "url": "https://arbitrum.drpc.org",
        "method": "eth_getUncleCountByBlockNumber",
        "status": 200
    }],
    [{
        "url": "https://arb1.arbitrum.io/rpc",
        "method": "eth_maxPriorityFeePerGas",
        "status": 200
    }, {
        "url": "https://rpc.ankr.com/arbitrum",
        "method": "eth_maxPriorityFeePerGas",
        "status": 200
    }, {
        "url": "https://1rpc.io/arb",
        "method": "eth_maxPriorityFeePerGas",
        "status": 200
    }, {
        "url": "https://arb-mainnet.g.alchemy.com/v2/demo",
        "method": "eth_maxPriorityFeePerGas",
        "status": 200
    }, {
        "url": "https://arbitrum.blockpi.network/v1/rpc/public",
        "method": "eth_maxPriorityFeePerGas",
        "status": 200
    }, {
        "url": "https://arbitrum-one.public.blastapi.io",
        "method": "eth_maxPriorityFeePerGas",
        "status": 200
    }, {
        "url": "https://endpoints.omniatech.io/v1/arbitrum/one/public",
        "method": "eth_maxPriorityFeePerGas",
        "status": 200
    }, {
        "url": "https://arb-mainnet-public.unifra.io",
        "method": "eth_maxPriorityFeePerGas",
        "status": 200
    }, {
        "url": "https://arbitrum.api.onfinality.io/public",
        "method": "eth_maxPriorityFeePerGas",
        "status": 200
    }, {
        "url": "https://rpc.arb1.arbitrum.gateway.fm",
        "method": "eth_maxPriorityFeePerGas",
        "status": 200
    }, {
        "url": "https://arbitrum-one.publicnode.com",
        "method": "eth_maxPriorityFeePerGas",
        "status": 200
    }, {
        "url": "https://arbitrum.meowrpc.com",
        "method": "eth_maxPriorityFeePerGas",
        "status": 200
    }, {
        "url": "https://arbitrum.drpc.org",
        "method": "eth_maxPriorityFeePerGas",
        "status": 200
    }],
    [{
        "url": "https://1rpc.io/arb",
        "method": "eth_newPendingTransactionFilter",
        "status": 200
    }, {
        "url": "https://arb-mainnet.g.alchemy.com/v2/demo",
        "method": "eth_newPendingTransactionFilter",
        "status": 200
    }, {
        "url": "https://arbitrum.blockpi.network/v1/rpc/public",
        "method": "eth_newPendingTransactionFilter",
        "status": 200
    }, {
        "url": "https://endpoints.omniatech.io/v1/arbitrum/one/public",
        "method": "eth_newPendingTransactionFilter",
        "status": 200
    }, {
        "url": "https://arb-mainnet-public.unifra.io",
        "method": "eth_newPendingTransactionFilter",
        "status": 200
    }, {
        "url": "https://arbitrum.api.onfinality.io/public",
        "method": "eth_newPendingTransactionFilter",
        "status": 200
    }, {
        "url": "https://arbitrum-one.publicnode.com",
        "method": "eth_newPendingTransactionFilter",
        "status": 200
    }, {
        "url": "https://arbitrum.meowrpc.com",
        "method": "eth_newPendingTransactionFilter",
        "status": 200
    }],
    [{
        "url": "https://1rpc.io/arb",
        "method": "eth_uninstallFilter",
        "status": 200
    }, {
        "url": "https://arb-mainnet.g.alchemy.com/v2/demo",
        "method": "eth_uninstallFilter",
        "status": 200
    }, {
        "url": "https://arbitrum.blockpi.network/v1/rpc/public",
        "method": "eth_uninstallFilter",
        "status": 200
    }, {
        "url": "https://endpoints.omniatech.io/v1/arbitrum/one/public",
        "method": "eth_uninstallFilter",
        "status": 200
    }, {
        "url": "https://arb-mainnet-public.unifra.io",
        "method": "eth_uninstallFilter",
        "status": 200
    }, {
        "url": "https://arbitrum.api.onfinality.io/public",
        "method": "eth_uninstallFilter",
        "status": 200
    }, {
        "url": "https://arbitrum-one.publicnode.com",
        "method": "eth_uninstallFilter",
        "status": 200
    }, {
        "url": "https://arbitrum.meowrpc.com",
        "method": "eth_uninstallFilter",
        "status": 200
    }, {
        "url": "https://api.zan.top/node/v1/arb/one/public",
        "method": "eth_uninstallFilter",
        "status": 200
    }],
    [{
        "url": "https://arb-mainnet.g.alchemy.com/v2/demo",
        "method": "net_listening",
        "status": 200
    }, {
        "url": "https://rpc.arb1.arbitrum.gateway.fm",
        "method": "net_listening",
        "status": 200
    }, {
        "url": "https://arbitrum.drpc.org",
        "method": "net_listening",
        "status": 200
    }],
    [{
        "url": "https://arbitrum.drpc.org",
        "method": "net_peerCount",
        "status": 200
    }],
    [{
        "url": "https://arb1.arbitrum.io/rpc",
        "method": "net_version",
        "status": 200
    }, {
        "url": "https://rpc.ankr.com/arbitrum",
        "method": "net_version",
        "status": 200
    }, {
        "url": "https://1rpc.io/arb",
        "method": "net_version",
        "status": 200
    }, {
        "url": "https://arbitrum.blockpi.network/v1/rpc/public",
        "method": "net_version",
        "status": 200
    }, {
        "url": "https://arbitrum-one.public.blastapi.io",
        "method": "net_version",
        "status": 200
    }, {
        "url": "https://endpoints.omniatech.io/v1/arbitrum/one/public",
        "method": "net_version",
        "status": 200
    }, {
        "url": "https://arb-mainnet-public.unifra.io",
        "method": "net_version",
        "status": 200
    }, {
        "url": "https://arbitrum.api.onfinality.io/public",
        "method": "net_version",
        "status": 200
    }, {
        "url": "https://rpc.arb1.arbitrum.gateway.fm",
        "method": "net_version",
        "status": 200
    }, {
        "url": "https://arbitrum-one.publicnode.com",
        "method": "net_version",
        "status": 200
    }, {
        "url": "https://arbitrum.meowrpc.com",
        "method": "net_version",
        "status": 200
    }, {
        "url": "https://api.zan.top/node/v1/arb/one/public",
        "method": "net_version",
        "status": 200
    }, {
        "url": "https://arbitrum.drpc.org",
        "method": "net_version",
        "status": 200
    }],
    [{
        "url": "https://arb1.arbitrum.io/rpc",
        "method": "web3_sha3",
        "status": 200
    }, {
        "url": "https://rpc.ankr.com/arbitrum",
        "method": "web3_sha3",
        "status": 200
    }, {
        "url": "https://1rpc.io/arb",
        "method": "web3_sha3",
        "status": 200
    }, {
        "url": "https://arb-mainnet.g.alchemy.com/v2/demo",
        "method": "web3_sha3",
        "status": 200
    }, {
        "url": "https://arbitrum.blockpi.network/v1/rpc/public",
        "method": "web3_sha3",
        "status": 200
    }, {
        "url": "https://arbitrum-one.public.blastapi.io",
        "method": "web3_sha3",
        "status": 200
    }, {
        "url": "https://endpoints.omniatech.io/v1/arbitrum/one/public",
        "method": "web3_sha3",
        "status": 200
    }, {
        "url": "https://arb-mainnet-public.unifra.io",
        "method": "web3_sha3",
        "status": 200
    }, {
        "url": "https://arbitrum.api.onfinality.io/public",
        "method": "web3_sha3",
        "status": 200
    }, {
        "url": "https://arbitrum-one.publicnode.com",
        "method": "web3_sha3",
        "status": 200
    }, {
        "url": "https://arbitrum.meowrpc.com",
        "method": "web3_sha3",
        "status": 200
    }],
    [{
        "url": "https://arb1.arbitrum.io/rpc",
        "method": "web3_clientVersion",
        "status": 200
    }, {
        "url": "https://rpc.ankr.com/arbitrum",
        "method": "web3_clientVersion",
        "status": 200
    }, {
        "url": "https://1rpc.io/arb",
        "method": "web3_clientVersion",
        "status": 200
    }, {
        "url": "https://arb-mainnet.g.alchemy.com/v2/demo",
        "method": "web3_clientVersion",
        "status": 200
    }, {
        "url": "https://arbitrum.blockpi.network/v1/rpc/public",
        "method": "web3_clientVersion",
        "status": 200
    }, {
        "url": "https://arbitrum-one.public.blastapi.io",
        "method": "web3_clientVersion",
        "status": 200
    }, {
        "url": "https://endpoints.omniatech.io/v1/arbitrum/one/public",
        "method": "web3_clientVersion",
        "status": 200
    }, {
        "url": "https://arb-mainnet-public.unifra.io",
        "method": "web3_clientVersion",
        "status": 200
    }, {
        "url": "https://arbitrum.api.onfinality.io/public",
        "method": "web3_clientVersion",
        "status": 200
    }, {
        "url": "https://rpc.arb1.arbitrum.gateway.fm",
        "method": "web3_clientVersion",
        "status": 200
    }, {
        "url": "https://arbitrum-one.publicnode.com",
        "method": "web3_clientVersion",
        "status": 200
    }, {
        "url": "https://arbitrum.meowrpc.com",
        "method": "web3_clientVersion",
        "status": 200
    }, {
        "url": "https://api.zan.top/node/v1/arb/one/public",
        "method": "web3_clientVersion",
        "status": 200
    }, {
        "url": "https://arbitrum.drpc.org",
        "method": "web3_clientVersion",
        "status": 200
    }],
    [{
        "url": "https://arb1.arbitrum.io/rpc",
        "method": "eth_getLogs",
        "status": 200,
        "time": 1549
    }, {
        "url": "https://rpc.ankr.com/arbitrum",
        "method": "eth_getLogs",
        "status": 200,
        "time": 1342
    }, {
        "url": "https://1rpc.io/arb",
        "method": "eth_getLogs",
        "status": 200,
        "time": 611
    }, {
        "url": "https://arbitrum.blockpi.network/v1/rpc/public",
        "method": "eth_getLogs",
        "status": 200,
        "time": 335
    }, {
        "url": "https://endpoints.omniatech.io/v1/arbitrum/one/public",
        "method": "eth_getLogs",
        "status": 200,
        "time": 1391
    }, {
        "url": "https://arb-mainnet-public.unifra.io",
        "method": "eth_getLogs",
        "status": 200,
        "time": 558
    }, {
        "url": "https://arbitrum.api.onfinality.io/public",
        "method": "eth_getLogs",
        "status": 200,
        "time": 525
    }, {
        "url": "https://rpc.arb1.arbitrum.gateway.fm",
        "method": "eth_getLogs",
        "status": 200,
        "time": 761
    }, {
        "url": "https://arbitrum-one.publicnode.com",
        "method": "eth_getLogs",
        "status": 200,
        "time": 1201
    }, {
        "url": "https://arbitrum.meowrpc.com",
        "method": "eth_getLogs",
        "status": 200,
        "time": 385
    }, {
        "url": "https://arbitrum.drpc.org",
        "method": "eth_getLogs",
        "status": 200,
        "time": 5985
    }],
    [{
        "url": "https://1rpc.io/arb",
        "method": "eth_newFilter",
        "status": 200,
        "time": 622
    }, {
        "url": "https://arb-mainnet.g.alchemy.com/v2/demo",
        "method": "eth_newFilter",
        "status": 200,
        "time": 560
    }, {
        "url": "https://endpoints.omniatech.io/v1/arbitrum/one/public",
        "method": "eth_newFilter",
        "status": 200,
        "time": 670
    }, {
        "url": "https://arb-mainnet-public.unifra.io",
        "method": "eth_newFilter",
        "status": 200,
        "time": 757
    }, {
        "url": "https://arbitrum.api.onfinality.io/public",
        "method": "eth_newFilter",
        "status": 200,
        "time": 457
    }, {
        "url": "https://arbitrum-one.publicnode.com",
        "method": "eth_newFilter",
        "status": 200,
        "time": 1844
    }, {
        "url": "https://arbitrum.meowrpc.com",
        "method": "eth_newFilter",
        "status": 200,
        "time": 215
    }],
    [{
        "url": "https://1rpc.io/arb",
        "method": "eth_newBlockFilter",
        "status": 200,
        "time": 1721
    }, {
        "url": "https://arb-mainnet.g.alchemy.com/v2/demo",
        "method": "eth_newBlockFilter",
        "status": 200,
        "time": 681
    }, {
        "url": "https://arbitrum.blockpi.network/v1/rpc/public",
        "method": "eth_newBlockFilter",
        "status": 200,
        "time": 849
    }, {
        "url": "https://endpoints.omniatech.io/v1/arbitrum/one/public",
        "method": "eth_newBlockFilter",
        "status": 200,
        "time": 615
    }, {
        "url": "https://arb-mainnet-public.unifra.io",
        "method": "eth_newBlockFilter",
        "status": 200,
        "time": 952
    }, {
        "url": "https://arbitrum.api.onfinality.io/public",
        "method": "eth_newBlockFilter",
        "status": 200,
        "time": 1058
    }, {
        "url": "https://arbitrum-one.publicnode.com",
        "method": "eth_newBlockFilter",
        "status": 200,
        "time": 1437
    }, {
        "url": "https://arbitrum.meowrpc.com",
        "method": "eth_newBlockFilter",
        "status": 200,
        "time": 617
    }]
]

module.exports = { inputArray }